### PR TITLE
fix: add type constraint for custom auth handlers

### LINKED ISSUE #49: SDK: Custom Authentication Extension causes several type problems
### Describe the Bug

Hello,

in terms of creating a own implementation of a custom authentication functionality, I discovered several typing problems with the current solution of extending directus with a custom authentication.

I've used the following https://docs.directus.io/reference/sdk.html#auth to implement a custom auth.

I created a login for metamask wallet users, to log in into directus by wallet.
By using the IAuth interface, i was not able to overwrite the AuthCredentials (email, password, otp?) so I had to use several generic typings, to get this work through the projects linter. This might be issued some day, to prevent typing problems over and over again.

`// eslint-disable-next-line @typescript-eslint/no-explicit-any
      await (sdk.auth as any).loginWithWallet({
        wallet_address: walletAddress,
        signature,
      });`

Same goes for the backend, which is currently not able to be extended somehow, because auth providers are fixed set and cannot be added.

Currently I am not able to login via different auth providers (for example my own provider for wallet logins) and need to be logged in via email +. password.

### To Reproduce

- Create a CustomAuthHandler according to https://docs.directus.io/reference/sdk.html#auth 
- Run Linter

### Errors Shown

_No response_

### What version of Directus are you using?

9.16.1

### What version of Node.js are you using?

16.6

### What database are you using?

postgres

### What browser are you using?

chrome

### How are you deploying Directus?

docker

### PR DESCRIPTION
**Pull request by heilmela**
fixes #49

The type constraint narrows down the type of `sdk.auth` and allows for more advanced extensions besides overriding existing methods. (which is rather useless in most cases)

As described in #49 now `sdk.auth.loginWithWallet` would be correctly typed and removes the necessity of casting e.g. `(sdk.auth as CustomAuth).loginWithWallet` is not necessary anymore.

I added a test to illustrate how unpleasant the extension of the auth handler currently is. 
It's bizarre that the transport calls the auth handler before the auth handler is assigned which leads in the test case to the linter magic comment in line 28.

### CODE REVIEW

File: src/base/directus.ts [hunk 1]
```diff
@@ -116,14 +116,14 @@ export class Directus<T extends TypeMap> implements IDirectus<T> {
 				transport: this._transport,
 				storage: this._storage,
 				...this._options?.auth,
-			} as AuthOptions);
+			} as AuthOptions) as unknown as IAuthHandler;
```
Comment (rijkvanzanten) [inline src/base/directus.ts:119]: Any way around having to cast to unknown first? 🤔

**Comment by rijkvanzanten** [comment]
Paging TS maestro @jonahgoldwastaken 🔔 😄

File: src/base/directus.ts (hunk 1 above)
Comment (jonahgoldwastaken) [reply src/base/directus.ts:119]: Yes, that is possible by properly casting the IAuthHandler type from what is passed into `options.auth` when creating a new Directus class

Comment (jonahgoldwastaken) [reply src/base/directus.ts:119]: Doing so is quite a hassle and requires very convoluted typing. The `unknown` here is very harmless and actually a suggestion TS gives you if the type you're trying to cast is correct otherwise, which it is in this situation.

Comment (heilmela) [reply src/base/directus.ts:119]: Just to make sure we are on the same page, the TS compiler, unfortunately, doesn't allow to assign of the subtype `IAuth` to the type constraints, because the type constraint `IAuthHandler` is the more general type. The only thing which would work is `this._auth = x as IAuth as IAuthHandler` (so instead of unknown we cast to IAuth) however casting is necessary and avoiding the unknown here doesn't improve anything. It may only make any linter happy.

Comment (heilmela) [reply src/base/directus.ts:119]: There is a good TS issue explaining that
https://github.com/microsoft/TypeScript/issues/49158

**Review by xsliii — APPROVED** [review]

**Review by rijkvanzanten — APPROVED** [review]
